name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build

  qoddi_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v2.0.4
        env:
          webhook_url: ${{ secrets.QODDI_DEPLOY_WEBHOOK }}
          webhook_secret: "Top Secret"
