name: Qoddi Deploy

on:
  push:
    branches: [ master ]

jobs:
  qoddi_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v2.0.4
      env:
        webhook_url: ${{ secrets.QODDI_DEPLOY_WEBHOOK }}
        webhook_secret: "Top Secret"
