name: Qoddi Deploy

on:
  push:
    branches: [ main ]

jobs:
  qoddi_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v2.0.4
      with:
        url: ${{secrets.QODDY_DEPLOY_WEBHOOK}}
